language: python
cache: pip
dist: bionic

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.2,<3.0"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master
    - gsoc2019

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jslint

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - ./run-qa-checks
  - coverage run --source=django_netjsonconfig runtests.py

after_success:
  coveralls
